#!/bin/bash

tempFile="tempfile"

# Make the input row file
numOfRows=$(wc -l < $1)
numOfItems=$(wc -w < $1)
numOfCols=$(( numOfItems1 / numOfRows1 ))

sum=0

while read myLine1 && read myLine2 <&3
do
	colIndex=1

	while [[ $colIndex -le $numOfCols ]]
	do

		num1=$(echo $myLine1 | cut -d " " -f $colIndex) 
		num2=$(echo $myLine2 | cut -d " " -f $colIndex) 

		sum=$(( num1 + num2 ))	


		if [[ $colIndex -lt $numOfCols ]]
		then
			echo -e -n  "$sum\t" >> $tempFile
		else 
			echo $sum >> $tempFile
		fi

		(( colIndex++ ))
	done

done < $1 3< $2

cat $tempFile
rm $tempFile
