#!/bin/bash

tempFile="tempfile"

# Make the input row file
numOfRows1=$(wc -l < $1)
numOfItems1=$(wc -w < $1)
numOfCols1=$(( numOfItems1 / numOfRows1 ))

numOfRows2=$(wc -l < $2)
numOfItems2=$(wc -w < $2)
numOfCols2=$(( numOfItems2 / numOfRows2 ))

colIndex=1

while [[ $colIndex -le $numOfCols1 ]]
do 
	sum=0
	while read myLine1 && read myLine2 <&3
	do

		index=1
		for num in $myLine1
		do
			num2=$(echo myLine2 | cut -d " " -f $index)
			echo $(( $num + num2 ))
			$(( index++ ))
			echo $num
		done
#		num1=$(echo $myLine1 | cut -d " " -f $colIndex) 
#		num2=$(echo $myLine2 | cut -d " " -f $colIndex) 

#		sum=$(( num1 + num2 ))	

#		echo $sum

	done < $1 3< $2


	(( colIndex++ ))	
done

#cat $tempFile
#rm $tempFile
