#!/bin/bash

# matrix dims [MATRIX]
# dims should print the dimensions of the matrix as the number of rows, followed by a space, then the number of columns.
# $ cat m1
# 1     2       3       4
# 5     6       7       8
# $ ./matrix dims m1
# 2 4

SRC="${0%/*}"
i1=$1
i2=$2

function dimens() {

echo; echo "Start of dimens function"
echo "Inputs: " $i1 $i2

# Initialize the row counts
row=0
col=0

read firstline < $i2
for i in $firstline
do
        ((col++))
done

while read myLine
do
        ((row++))
done < "$i2"
echo $row $col
}

echo
echo "Input \$1: $1"
echo "Input \$2: $2"

if [[ $1 == "dims" ]]
then
	echo
	echo "Input 1 == dimens"
	echo "Launching dimens() function"
	dimens
fi
