#!/bin/bash

tempFile="tempfile"

# Make the input row file
numOfRows=$(wc -l < $1)
numOfItems=$(wc -w < $1)
numOfCols=$(( numOfItems / numOfRows ))


colIndex=1

while [[ $colIndex -le $numOfCols ]]
do 
	sum=0
	while read myLine
	do
		num=$(echo $myLine | cut -d " " -f $colIndex)
		sum=$(( sum + num )) 
	done < $1

	(( mean= ($sum + ($numOfRows / 2) *(($sum > 0) * 2 - 1)) / $numOfRows ))

	echo -n $mean >> $tempFile

	if [[ $colIndex -lt $numOfCols ]]
	then
		echo -n -e '\t' >> $tempFile 
	else
		echo >> $tempFile
	fi

	(( colIndex++ ))	
done

cat $tempFile
rm $tempFile
