#!/bin/bash

tempFile="tempfile"

# Make the input row file
numOfRows=$(wc -l < $1)
numOfItems=$(wc -w < $1)
numOfCols=$(( numOfItems / numOfRows ))

index=1
echo $1
cat $1
echo $numOfRows "x" $numOfCols
echo "Total: " $numOfItems
echo "Index: " $index
echo

#cat $1 | paste -s -d '\t' $1 > $tempFile

while [[ $index -le $numOfCols ]]
do 

	echo "Index: " $index
	
	while read myLine
	do
		echo $myLine | cut -d " " -f $index
	done < $1


	echo "Index: " $index
	(( index++ ))	

done

